# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Project Automator
on: [pull_request]

jobs:
  label:

    runs-on: ubuntu-latest

    steps:
    - name: "Assign to project"
      uses: peter-evans/create-or-update-project-card@v1
      with:
          project-name: Pull Requests
          column-name: Pending Review
